# Generated by Django 3.0.8 on 2020-07-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.TextField()),
                ('productDetail', models.TextField()),
                ('sec3', models.TextField()),
                ('sec5', models.TextField()),
                ('sec6', models.TextField()),
                ('purchaseView', models.TextField()),
            ],
            options={
                'db_table': 'product_detail_tags',
            },
        ),
    ]
