# Generated by Django 3.0.8 on 2020-07-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='SkinInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skinType', models.CharField(max_length=50, null=True)),
                ('skinTrouble', models.CharField(max_length=100, null=True)),
                ('skinSensitivity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'skin_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('account', models.CharField(default=' ', max_length=100)),
                ('password', models.CharField(default=' ', max_length=100)),
                ('birthday', models.DateField(default=0)),
                ('email', models.CharField(default=' ', max_length=200)),
                ('phoneNumber', models.CharField(default=' ', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('gender_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Gender')),
                ('skinInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SkinInfo')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
