# Generated by Django 3.0.8 on 2020-07-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200724_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinTrouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
            ],
            options={
                'db_table': 'skin_troubles',
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'skin_types',
            },
        ),
        migrations.CreateModel(
            name='UserSkinTrouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skinTrouble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SkinTrouble')),
            ],
            options={
                'db_table': 'user_skin_troubles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='skinSensitivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='SkinInfo',
        ),
        migrations.AddField(
            model_name='userskintrouble',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='skinTrouble',
            field=models.ManyToManyField(through='user.UserSkinTrouble', to='user.SkinTrouble'),
        ),
        migrations.AddField(
            model_name='user',
            name='skinType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.SkinType'),
        ),
    ]
