# Generated by Django 3.0.8 on 2020-07-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_component'),
        ('user', '0004_auto_20200725_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'likeproducts',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='likeProduct',
            field=models.ManyToManyField(through='user.LikeProduct', to='product.Product'),
        ),
    ]
